const  TYPES = {

    // login

    AUTHLOGIN : "[AUTH] LOGIN",
    AUTHLOGOUT : "[AUTH] LOGOUT",

    // spend

    SPENDADDNEW : "[SPEND] NEW SPEND",
    SPENDACTIVE : "[SPEND] SET ACTIVE SPEND",
    SPENDLOAD : "[SPEND] LOAD SPENDS",
    SPENDUPDATE: "[SPEND] UPDATE SPEND",
    SPENDDELETE: "[SPEND] DELETE SPEND",
    SPENDLOGOUT: "[SPEND] LOGOUT CLEANING",

    //savings

    SAVINGSNEW : "[SAVING] NEW SAVING",
    SAVINGACTIVE: "[SAVING] SET ACTIVE SAVING",
    SAVINGLOAD:" [SAVING] LOAD SAVINGS",
    SAVINGUPDATE : "[SAVING] UPDATE SAVING",
    SAVINGDELETE: "[SAVING] DELETE SAVING",
    SAVINGLOGOUT: "[SAVIND] LOGOUT CLEANING",

    //Task

    TODONEW : "[TODO] NEW TODO",
    TODOACTIVE : "[TODO] SET ACTIVE TODO",
    TODOLOAD : "[TODO] LOAD TODOS",
    TODODONE : "[TODO] DONE TODO",
    TODOUPDATE: "[TODO] UPDATE TODO",
    TODODELETE: "[TODO] DELETE",
    TODOLOGOUT: "[TODO] LOGOUT CLEANING",


    //data

    DATATOTALSAVED: "[DATA] SET TOTAL SAVED",
    DATAMOSTVALUESAVED: "[DATA] SET MOST VALUE SAVED",

    DATATOTALSPENT: "[DATA] SET TOTAL SPENT",
    DATAMOSTVALUESPENT: "[DATA] SET MOST VALUE SPENT",

    DATAUNDONETAKS: "[DATA] SET UNDONE TASK",
    DATADONETAKS: "[DATA] SET DONE TASK",
    DATATAKSWITHALERT: "[DATA] SET TASK WITH ALERT",

    //UI
    UIOPENALERTTODOMODAL : "[UI] OPEN MODAL ALERT TODO",
    UICLOSEALERTTODOMODAL : "[UI] CLOSE MODAL ALERT TODO",
    UISETALREADYOPENMODAL : "[UI] CLOSE MODAL ALREADY OPEN",
}


export default TYPES