const  TYPES = {

    // login

    AUTHLOGIN : "[AUTH] LOGIN",
    AUTHLOGOUT : "[AUTH] LOGOUT",

    // spend

    SPENDADDNEW : "[SPEND] NEW SPEND",
    SPENDACTIVE : "[SPEND] SET ACTIVE SPEND",
    SPENDLOAD : "[SPEND] LOAD SPENDS",
    SPENDUPDATE: "[SPEND] UPDATE SPEND",
    SPENDDELETE: "[SPEND] DELETE SPEND",
    SPENDLOGOUT: "[SPEND] LOGOUT CLEANING",

    //savings

    SAVINGSNEW : "[SAVING] NEW SAVING",
    SAVINGACTIVE: "[SAVING] SET ACTIVE SAVING",
    SAVINGLOAD:" [SAVING] LOAD SAVINGS",
    SAVINGUPDATE : "[SAVING] UPDATE SAVING",
    SAVINGDELETE: "[SAVING] DELETE SAVING",
    SAVINGLOGOUT: "[SAVIND] LOGOUT CLEANING",

    //Task

    TODONEW : "[TODO] NEW TODO",
    TODOACTIVE : "[TODO] SET ACTIVE TODO",
    TODOLOAD : "[TODO] LOAD TODOS",
    TODODONE : "[TODO] DONE TODO",
    TODOUPDATE: "[TODO] UPDATE TODO",
    TODODELETE: "[TODO] DELETE",
    TODOLOGOUT: "[TODO] LOGOUT CLEANING"




}


export default TYPES