const  TYPES = {

    // login

    AUTHLOGIN : "[AUTH] LOGIN",
    AUTHLOGOUT : "[AUTH] LOGOUT",

    // spend

    SPENDADDNEW : "[SPEND] NEW SPEND",
    SPENDACTIVE : "[SPEND] SET ACTIVE SPEND",
    SPENDLOAD : "[SPEND] LOAD SPENDS",
    SPENDUPDATE: "[SPEND] UPDATE SPEND",
    SPENDDELETE: "[SPEND] DELETE SPEND",
    SPENDLOGOUT: "[SPEND] LOGOUT CLEANING"
}


export default TYPES